### PR TITLE
Validate e-mail addresses

### LINKED ISSUE #51: Invalid emails are accepted in /signup
## Current behavior
`POST /signup` accepts invalid emails.

## Expected behavior
Emails should be validated, and invalid emails should not be accepted.

### PR DESCRIPTION
**Pull request by Xertes0**
Validate e-mail addresses using RFC 5322 compliant regex. Validation happens on:
 - /signup POST
 - /user PATCH, POST, PUT

### CODE REVIEW

**Review by papaj-na-wrotkach — CHANGES_REQUESTED** [review]
document the possible status code 400 in swagger on every endpoint if not already documented

**Comment by papaj-na-wrotkach** [comment]
btw I think only `patchOne` endpoint in `UserController` needs the change bc the rest already has it

**Comment by Xertes0** [comment]
> btw I think only `patchOne` endpoint in `UserController` needs the change bc the rest already has it

Could you elaborate?

**Comment by papaj-na-wrotkach** [comment]
I mean that only PATCH endpoint doesn't have HTTP 400 status documented from all of the endpoints that should have it documented

**Comment by Xertes0** [comment]
> I mean that only PATCH endpoint doesn't have HTTP 400 status documented from all of the endpoints that should have it documented

Oh, I though you were referring to the email validation. Now I understand.

**Review by papaj-na-wrotkach — APPROVED** [review]

**Pull request merged**
