### PR TITLE
improve offer searching

### LINKED ISSUE #57: Add owner_id filter to search places endpoint
Currently, there is no filter for searching places by owner_id in the search places endpoint. 
To make it easier for users to retrieve all places with a particular owner's id without having to manually enter the id, I propose adding an owner_id filter to the endpoint.

@papaj-na-wrotkach suggested this solution and I agree that it would be a useful addition. Therefore, I am creating this issue to track the implementation of this feature.

Proposed Changes:

-     Add a filter for owner_id to the search places endpoint.
-     Update the documentation to reflect the new filter.

### PR DESCRIPTION
**Pull request by papaj-na-wrotkach**
fix for #57

### CODE REVIEW

**Comment by papaj-na-wrotkach** [comment]
for now only for offer controller, but if everything is working fine I'll change other controllers likewise

**Comment by kamikos** [comment]
It's good waiting for [place-controller](http://localhost:8000/swagger/ui#/place-controller) with simillar approach

**Comment by papaj-na-wrotkach** [comment]
okay, will do

**Comment by papaj-na-wrotkach** [comment]
done, probably

**Pull request merged**
