### PR TITLE
SQLite triggers removing dangling offers and places

### LINKED ISSUE #49: Offers should be deleted along with places they are linked to
## Current behavior
When deleting a place by `DELETE /place` endpoint, offers that were linked to that offer are not deleted.

## Expected behavior
Offers should be deleted along with places they are linked to.

### PR DESCRIPTION
**Pull request by Xertes0**
- Offers pointing to a place that was deleted, will be removed.
- Places owned by a user that was deleted, will be removed.

### CODE REVIEW

**Comment by papaj-na-wrotkach** [comment]
I moved your changes to existing triggers

**Review by papaj-na-wrotkach — APPROVED** [review]

**Comment by Xertes0** [comment]
> I moved your changes to existing triggers

If you want to mix the triggers together, then I think grouping them together, like I did in the latest commit, would be good.

**Comment by Xertes0** [comment]
BTW, when we end up merging this, do you mind if I squash the commits, and co-author you?

**Comment by papaj-na-wrotkach** [comment]
No problem, you can

**Pull request merged**
