### PR TITLE
return HTTP status 201 instead of 200 in POST and PUT endpoints

### LINKED ISSUE #48: POST and PUT requests should return 201 - Created, when new entry was created
## Current behavior
When making a POST or PUT request to any offer or place endpoint, which results in creating a new offer or a new place, server responds with 200.

## Expected behavior
In this situation, server should respond with 201.

### PR DESCRIPTION
**Pull request by papaj-na-wrotkach**

### CODE REVIEW

**Comment by Xertes0** [comment]
Did you also change PATCH endpoints? They still seem to return 200, when a new place/offer was created.

**Comment by papaj-na-wrotkach** [comment]
Only PUT and POST as we agreed

**Comment by Xertes0** [comment]
> Only PUT and POST as we agreed

Okay, but PATCH should also be changed.

**Review by Xertes0 — APPROVED** [review]
LGTM 👍🏻

**Comment by Xertes0** [comment]
Follow up: #67

**Pull request merged**
